### PR TITLE
My Work - v2

### PR DESCRIPTION
**Pull request by HmanA6399**
CHANGES
1. Modified back/index.js to add 2 new endpoint, "post:/message" and "get:/contactInfo"
2. Added "back/models" with 2 new models, one for contactInfo and the other for messages
3. Modified "back/mongo.js" to add the suitable link of Mongo Atlas DB
4. Added /pages/ContactsPage
5. Modified /globals/routes.js to add a new route for the contacts page
6. Fixing issue in /pages/HomePage/components/Committees

LIBRARIES
1. Axios >> https://github.com/axios/axios
2. Nodemon - as DevDep -

-- so please accept the changes in node_modules, package.json and package_lock.json and if accepted, please add the packages to README.md--

### CODE REVIEW

**Comment by HmanA6399** [comment]
Thanks for your review.
Unfortunately, due to some studying duties I'll not be able to do these
before Thursday 14/11 10:00PM. So by this time I'll have done them and PR'd
them as well.

**Comment by mohamedsaad4** [comment]
Ok, I'll do some changes to add the `ContactsPage` and I'll leave the rest for u.

**Comment by dvmhmdsd** [comment]
Thanks very much for your awesome work. 
I'll merge it, but try to: 

1. separate all the utilities in the contactForm Component in the front.

2. Test the front & the back please.

**Comment by HmanA6399** [comment]
Thank you for the review.
I'll try both with deadline Fri 6/12 11:59PM isA

**Pull request merged**
